---
title: "GoF of valued ERGMs fitted to pooled data"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, cache=FALSE}
library(ggplot2)
library(ergm.count)
requireNamespace("box")
box::use(
  funs.gof = codebox/gof,
  funs.utils = codebox/misc[...]
)

knitr::opts_chunk$set(
  echo = FALSE
  )

r_cores <- max(2, get_r_cores())
```




# Model 1

```{r model1-load}
fit <- readRDS("ergm-pooled1.rds")
```

Summary:

```{r model1-summary}
summary(fit)
```

```{r model1-gof-setup}
nsims <- 500
```

GOF is based on `r nsims` simulated networks.

```{r model1-simulate}
set.seed(666)
simnets <- simulate(fit, nsim = 500)
```


## Degree distribution

```{r model1-gof-degree, fig.width=7, fig.height=12}
dat <- funs.gof$gofplot_degrees(fit, simnets)

dat$simulated |>
  ggplot(aes(x=deg, y = n, group = deg)) +
  geom_boxplot(aes(color = "simulated"), key_glyph = draw_key_path) +
  geom_line(aes(x = deg, y = n, group = NULL, color = "observed"), 
            data = dat$observed, key_glyph = draw_key_path) +
  facet_wrap(~ season, ncol = 4) +
  xlab("Degree (weighted)") +
  ylab("Frequency") +
  scale_color_manual(
    name = "Simulated / Observed",
    values = c(simulated = "black", observed = "red"),
    labels = c("Simulated", "Observed")
  ) +
  theme(
    legend.position = "top"
  )
```



## Mixing matrix

```{r, eval=FALSE}
# Observed
obs <- funs.gof$nba_summary(fit$network ~ mm(div ~ div)) |>
  dplyr::mutate(
    div_pair = paste0(
      stringi::stri_extract_first_regex(name, "(?<=div=)[A-Za-z]+(?=,)") |>
        substr(1, 1),
      "-",
      stringi::stri_extract_first_regex(name, "(?<=div=)[A-Za-z]+(?=\\])") |>
        substr(1,1)
    )
  )
    



# Simulated

library(parallel)
cl <- makeCluster(r_cores)
clusterExport(cl, c("summary_formula", "funs.gof"))


l <- parLapply(
  cl, 
  simnets, 
  function(net) funs.gof$nba_summary(net ~ mm(div ~ div))
)

stopCluster(cl)

l |>
  dplyr::bind_rows(.id = "simid") |>
  dplyr::mutate(
    div_pair = paste0(
      stringi::stri_extract_first_regex(name, "(?<=div=)[A-Za-z]+(?=,)") |>
        substr(1, 1),
      "-",
      stringi::stri_extract_first_regex(name, "(?<=div=)[A-Za-z]+(?=\\])") |>
        substr(1,1)
    )
  ) -> d


d |>
  ggplot(aes(x=div_pair, y = value)) +
  geom_boxplot() +
  geom_point(aes(x=div_pair, y = value), color = "red", data = obs) +
  facet_wrap(~ season, scales = "free_x") +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5)
  )

```





# Model 2

Seasons 1976-2004.

```{r model2-load}
fit <- readRDS("ergm-pooled2.rds")
```

Summary:

```{r model2-summary}
summary(fit)
```

```{r model2-gof-setup}
nsims <- 500
```

GOF is based on `r nsims` simulated networks.

```{r model2-simulate}
set.seed(666)
simnets <- simulate(fit, nsim = 500)
```

## Degree distribution

```{r model2-gof-degree, fig.width=7, fig.height=12}
dat <- funs.gof$gofplot_degrees(fit, simnets)

dat$simulated |>
  ggplot(aes(x=deg, y = n, group = deg)) +
  geom_boxplot(aes(color = "simulated"), key_glyph = draw_key_path) +
  geom_line(aes(x = deg, y = n, group = NULL, color = "observed"), 
            data = dat$observed, key_glyph = draw_key_path) +
  facet_wrap(~ season, ncol = 4) +
  xlab("Degree (weighted)") +
  ylab("Frequency") +
  scale_color_manual(
    name = "Simulated / Observed",
    values = c(simulated = "black", observed = "red"),
    labels = c("Simulated", "Observed")
  ) +
  theme(
    legend.position = "top"
  )
```



# Model 3

Seasons 2005-2019.

```{r model3-load}
fit <- readRDS("ergm-pooled3.rds")
```

Summary:

```{r model3-summary}
summary(fit)
```

```{r model3-gof-setup}
nsims <- 500
```

GOF is based on `r nsims` simulated networks.

```{r model3-simulate}
set.seed(666)
simnets <- simulate(fit, nsim = 500)
```

## Degree distribution

```{r model3-gof-degree, fig.width=7, fig.height=12}
dat <- funs.gof$gofplot_degrees(fit, simnets)

dat$simulated |>
  ggplot(aes(x=deg, y = n, group = deg)) +
  geom_boxplot(aes(color = "simulated"), key_glyph = draw_key_path) +
  geom_line(aes(x = deg, y = n, group = NULL, color = "observed"), 
            data = dat$observed, key_glyph = draw_key_path) +
  facet_wrap(~ season, ncol = 4) +
  xlab("Degree (weighted)") +
  ylab("Frequency") +
  scale_color_manual(
    name = "Simulated / Observed",
    values = c(simulated = "black", observed = "red"),
    labels = c("Simulated", "Observed")
  ) +
  theme(
    legend.position = "top"
  )
```



<!-- Include folded session info -->
<details>
<summary>Session info</summary>
```{r session-info}
sessioninfo::session_info()
```
</details>
